---
# tasks file setup-RedHat

- name: Adding MariaDB Galera Repo.
  template:
    src: mariadb-galera.repo.j2
    dest: /etc/yum.repos.d/mariadb-galera.repo
    mode: 0644
    owner: root
    group: root
  when: mariadb_repo

- name: "[CentOS] Ensure MariaDB packages are installed."
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ __mariadb_packages }}"
- name: "[CentOS] Ensure MariaDB packages are installed."
  yum:
    name: "firewalld"
    state: installed
- name: Enable firewalld
  service: name=firewalld state=started enabled=yes
  - name: openfirewalld ports for galera
  when: install_muninnode|default(True)
  command: firewall-cmd --permanent --zone=dmz --add-rich-rule='rule family="ipv4" source address="{{ item }}/32" port port=4949 protocol="tcp" accept'
